services:
  - type: web
    name: mind-recommend-api
    env: python
    region: singapore  # Choose a region close to your users
    plan: free  # Use the free plan
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://mind-recommend.vercel.app
      - key: PYTHON_VERSION
        value: 3.10.13
